# The version number of this file format
meta:
  version: 1.0.0
# The front end versions that support this file format version 
frontend:
  version: ">=1.0.2"
# The framework version this store file applies to
framework:
  version: =3.0.0
  github-tag: 'v3.0.0' # Or branch
  github-sha: f2422c6bc43d2d20251e4f66af70514112a77441
# When this store was created
timestamp: ~
# Which certificate signed the modules in this store
signer: default
supported-languages:
  - en
# The extensions defined in this store
extensions:
# The list of extensions
  list:
# An extension content has two parts:
# - definition: defines the name, version, type, etc.
# - sources: defines where to get content parts, such as the description, or the package, or the source
    - definition:
        name: files
        type: module
        version: 1.0.0
      contents:
        # If defined, at this level, applies to both description and package. 
        # Uses all defaults as known today (default locations for locale files)
        # This part sets up the building for this module and the description uploading
        source:
          method: github
          url: UnofficialCrusaderPatch/extension-files
          github-sha: f3ba001af4d8116fbeb9183c51a27ce29d052c3c
          github-tag: main
    - definition:
        name: aiSwapper
        version: 1.1.0
        type: module
      contents:
        # If defined, at this level, applies to both description and package. 
        # Uses all defaults as known today (default locations for locale files)
        # This part sets up the building for this module and the description uploading
        source:
          method: github
          url: UnofficialCrusaderPatch/extension-aiSwapper
          github-sha: f779b9a2bd5a9691b8bbfc9459af019b5ad29f85
          github-tag: main
    - definition:
        name: ucp2-legacy-defaults
        version: 2.15.1
        type: plugin
      contents:
        source:
          method: github
          url: UnofficialCrusaderPatch/extension-ucp2-legacy-defaults
          github-sha: 68ef49205cc604311f230ef462b0cebf18e74e9d
          github-tag: main

   