# The version number of this file format
meta:
  version: 1.0.0
# The front end versions that support this file format version 
frontend:
  version: ">=1.0.2"
# The framework version this store file applies to
framework:
  version: =3.0.0
# When this store was created
timestamp: 2024-07-31T19:11:08.975Z
# Which certificate signed the modules in this store
signer: UCP-Team-key-1
# The extensions defined in this store
extensions:
# The list of extensions
  list:
# An extension content has two parts:
# - definition: defines the name, version, type, etc.
# - sources: defines where to get content parts, such as the description, or the package, or the source
    - definition:
        name: online-module-test-one
        type: module
        url: Where to find more INFO
        author: authors
        version: 0.0.1
        dependencies: {}
        display-name: "Online Module #1"
      contents:
        # If defined, at this level, applies to both description and package. 
        # Uses all defaults as known today (default locations for locale files)
        # This part sets up the building for this module and the description uploading
        source:
          method: github-zip
          url: https://github.com/owner/repo
          github-sha: 9b35f668b6312a344a70999cedcc82bb1770f921
          signer: default # Optional
          location: # Optional
            root: 
              default: true
          targets: [description, package] # Optional
        description:
          - language: default
            method: online
            type: markdown
            url:  set by recipe based on based on "source"
            # If defined at this level custom things can be defined applicable to this entry only
            source:
              method: github-zip
              url: https://github.com/owner/repo
            # i.e., fetch content at: https://github.com/owner/repo/archive/9b35f668b6312a344a70999cedcc82bb1770f921.zip
              github-sha: 9b35f668b6312a344a70999cedcc82bb1770f921
              location: # Optional
              default: true
        package:
          - method: set by recipe based on "source"
            size: set by recipe based on "source"
            url: set by recipe based on "source"
            signer: set by recipe based on "source"
            hash: set by recipe based on "source"
            signature: set by recipe based on "source"

    - definition:
        name: online-plugin-test-two
        type: plugin
        url: Where to find more INFO
        author: authors
        version: 0.0.1
        dependencies: {}
        display-name: "Online Plugin #2"
      sources:
        description:
          - language: default
            method: online
            url: https://raw.githubusercontent.com/UnofficialCrusaderPatch/extension-ucp2-evrey-aiv/main/README.md
        package:
          - method: zip
            type: plugin
            url: stub
            size: 2000000
    - definition:
        name: online-module-test-three
        type: plugin
        url: Where to find more INFO
        author: authors
        version: 0.0.1
        dependencies: {}
        display-name: "Online Plugin #3"
      sources:
        description:
          - language: default
            method: online
            url: https://raw.githubusercontent.com/UnofficialCrusaderPatch/extension-ucp2-evrey-aiv/main/README.md
          - language: default
            method: inline
            content: Hello!
        package:
          - method: zip
            type: plugin
            url: stub
            size: 2000000
    - definition:
        name: Legends-Of-The-Orient
        display-name: Legends Of The Orient
        author: Crusader Pilaw
        version: 3.0.1
        dependencies:
          Legends-Of-The-Orient-AI: ^3.0.1
          framework: ">=3.0.1"
          frontend: ">=1.0.2"
          ucp2-legacy: ^2.15.1
          startResources: ^1.0.0
          maploader: ^1.0.0
        type: plugin
      sources:
        description:
          - language: default
            method: online
            url: https://raw.githubusercontent.com/CrusaderPilaw/extension-Legends-of-the-Orient/main/locale/description-en.md
          - language: default
            method: inline
            content: Hello!
        package:
          - method: github-zip
            type: plugin
            url: https://github.com/CrusaderPilaw/extension-Legends-of-the-Orient/archive/9b35f668b6312a344a70999cedcc82bb1770f921.zip
            size: 15000000
    - definition:
        name: Legends-Of-The-Orient-AI
        display-name: Legends Of The Orient AI
        author: Crusader Pilaw
        version: 3.0.1
        dependencies:
          framework: ">=3.0.1"
          frontend: ">=1.0.2"
          aiSwapper: ^1.1.0
        type: plugin
      sources:
        description:
          - language: default
            method: online
            url: https://raw.githubusercontent.com/CrusaderPilaw/extension-Legends-of-the-Orient-AI/main/locale/description-en.md
          - language: default
            method: inline
            content: Hello!
        package:
          - method: github-zip
            type: plugin
            url: https://github.com/CrusaderPilaw/extension-Legends-of-the-Orient-AI/archive/371103bdcd876eea9c005943cf749bbdadf77981.zip
            size: 280000000
    - definition:
        name: Legends-Of-The-Orient-AI
        display-name: Legends Of The Orient AI
        author: Crusader Pilaw
        version: 3.0.0
        dependencies:
          framework: ">=3.0.1"
          frontend: ">=1.0.2"
          aiSwapper: ^1.1.0
        type: plugin
      sources:
        description:
          - language: default
            method: online
            url: https://raw.githubusercontent.com/CrusaderPilaw/extension-Legends-of-the-Orient-AI/main/locale/description-en.md
          - language: default
            method: inline
            content: Hello!
        package: []