name: Build modules

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  workflow_dispatch

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .
  UCP3_DIR: UnofficialCrusaderPatch3-3.0.0

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build_configuration: [Release]
    env:
        BUILD_CONFIGURATION: ${{ matrix.build_configuration }}
    steps:
    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.UCP3_PRIVATE_REPO_READ_ACCESS }}
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Run build script for UnofficialCrusaderPatch3
      shell: pwsh
      env:
        UCP3_NUGET_TOKEN: ${{ secrets.UCP3_READ_PACKAGES }}
      run: |
        pushd UnofficialCrusaderPatch3*
        
        .\build.ps1 -Build "$env:BUILD_CONFIGURATION" -NugetToken "$env:UCP3_NUGET_TOKEN"
        
        popd

    - name: Run build script for the modules
      shell: pwsh
      env:
        UCP3_NUGET_TOKEN: ${{ secrets.UCP3_READ_PACKAGES }}
      run: |
        .\build.ps1 -Build "$env:BUILD_CONFIGURATION" -NugetToken "$env:UCP3_NUGET_TOKEN"

    - name: Display ref name
      shell: pwsh
      run: |
        echo $env:GITHUB_REF_NAME
        echo $env:GITHUB_REF

    - name: Create release 
      uses: 'marvinpinto/action-automatic-releases@latest'
      with:
        repo_token: '${{ secrets.GITHUB_TOKEN }}'
        automatic_release_tag: '${{ env.GITHUB_REF_NAME  }}'
        prerelease: true
        draft: false
        title: 'Build for ${{ env.GITHUB_REF_NAME }}'
        files: |
          build/${{ env.BUILD_CONFIGURATION }}/latest.json
          build/${{ env.BUILD_CONFIGURATION }}/*.zip
          build/${{ env.BUILD_CONFIGURATION }}/*.sig
