name: Build and release store

on:
  push

jobs:
  build:
    runs-on: windows-latest
    env:
        BUILD_CONFIGURATION: ReleaseSecure
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Prepare signing of modules by exporting secret to file
      shell: pwsh
      working-directory: ${{env.GITHUB_WORKSPACE}}
      env:
        UCP3_SIGNING_CERTIFICATE_CONTENTS: ${{ secrets.UCP3_SIGNING_CERTIFICATE_CONTENTS }}
      run: |
        Set-Content -Value "$env:UCP3_SIGNING_CERTIFICATE_CONTENTS" -Path "$($env:GITHUB_WORKSPACE)\ucp3-module-signing-key.pem" -Force

    - name: Build store
      shell: pwsh
      env:
        UCP3_NUGET_TOKEN: ${{ secrets.UCP3_READ_PACKAGES }}
      run: |
        .\scripts\build-store.ps1 -NugetToken "$env:UCP3_NUGET_TOKEN" -Certificate "$($env:GITHUB_WORKSPACE)\ucp3-module-signing-key.pem"

    - name: Release store
      shell: pwsh
      env:
        UCP3_NUGET_TOKEN: ${{ secrets.UCP3_READ_PACKAGES }}
      run: |
        .\scripts\create-release.ps1
